maintainer       "Benedikt Böhm"
maintainer_email "bb@xnull.de"
license          "Apache 2.0"
description      "Installs and configures Chef Client and Server"
version          "0.1"
supports         "gentoo"

depends "couchdb"
depends "nginx"
depends "openssl"
depends "portage"
depends "rabbitmq"
